@startuml Tasks
object Tasks {
    <#lightblue>|= Tasks: | Group member | Done? |
    <#white>| |
    <#white>|= Diagrams: | |
    <#white>| Sequence diagram | Mart, Michael | ✔|
    <#white>| Process flowchart |Angelique | |
    <#white>| Interface diagram |Angelique | |
    <#white>| State machine diagram |Esther| |
    <#white>| Visualization GIT workflow | | |
    <#white>| Time displacement diagram | | |
    <#white>| Electrical diagram | Esther | |
    <#white>| |
    <#white>|= Safety: | | 
    <#white>| Risk Assesment | Angelique, Esther | ✔ |
    <#white>| Performance analysis system |Esther | |
    <#white>| |
    <#white>|= Realization: | | 
    <#white>| Design system | Mart, Michael| ✔ |
    <#white>| Design gripper | Michiel | |
    <#white>| PLC programming | Michael | ✔ |
    <#white>| Printing parts | Mart | ✔ |
    <#white>| Assembly system | Mart, Michael | |
    <#white>| Wiring system | Mart, Michael | |
    <#white>| Robot Programming | Michael, Mart | |
    <#white>| |
    <#white>|= Finalizing: | |
    <#white>| Implementation review |Michael | |
    <#white>| Future improvements | Mart Angelique| |
    <#white>| Assignment analysis/description |Esther  | |
    <#white>| Collaboration contract / division of work | | |
    <#white>| Submitted documentation | | | 

  
}
@enduml